In [11]:
##Pkg.add("Images")
from PIL import Image

#Pkg.add("DataFrame")
##using Images
#using DataFrame

In [12]:
import pandas
import numpy as np

In [13]:
def read_data(typeData, labelsInfo, imageSize, path):
    #Intialize x matrix
    x = np.zeros(shape=(len(labelsInfoTrain), imageSize))

    for (index, idImage) in enumerate(labelsInfo["ID"]): 
        #Read image file 
        #nameFile = path+"/"+typeData+"Resized/"+idImage+".Bmp"
        nameFile="%s/%sResized/%s.Bmp" %(path,typeData,idImage)
        img = Image.open(nameFile).convert('L')

        #Transform image matrix to a vector and store 
        #it in data matrix 
        x[index, :] = np.reshape(img, (1, imageSize))
    
     
    return x


In [14]:
imageSize = 400 # 20 x 20 pixel


In [15]:
#Set location of data files, folders
path = "C://Users//cr203945//Documents//NEU//Image recognition Project"

In [16]:
labelsInfoTrain = pandas.read_csv("C://Users//cr203945//Documents//NEU//Image recognition Project//trainLabels.csv")

In [17]:
labelsInfoTrain


ID Class
0        1     n
1        2     8
2        3     T
3        4     I
4        5     R
5        6     W
6        7     L
7        8     l
8        9     K
9       10     G
10      11     A
11      12     A
12      13     C
13      14     u
14      15     t
15      16     A
16      17     N
17      18     I
18      19     O
19      20     k
20      21     l
21      22     D
22      23     T
23      24     u
24      25     w
25      26     N
26      27     E
27      28     E
28      29     H
29      30     e
...    ...   ...
6253  6254     E
6254  6255     2
6255  6256     i
6256  6257     P
6257  6258     T
6258  6259     9
6259  6260     S
6260  6261     I
6261  6262     N
6262  6263     A
6263  6264     m
6264  6265     S
6265  6266     a
6266  6267     q
6267  6268     i
6268  6269     o
6269  6270     I
6270  6271     n
6271  6272     t
6272  6273     S
6273  6274     e
6274  6275     l
6275  6276     O
6276  6277     R
6277  6278     L
6278  6279     N
6279  6280     I
6280  6281     P
6281  6282     N
6282  6283     R

[6283 rows x 2 columns]

In [18]:
xTrain = read_data("train", labelsInfoTrain, imageSize, path)
xTrain

array([[  62.,   63.,   88., ...,   70.,   69.,   71.],
       [ 118.,  118.,  118., ...,  116.,  116.,  115.],
       [  81.,   97.,   98., ...,   95.,   87.,   77.],
       ..., 
       [ 109.,  108.,  108., ...,  106.,  106.,  107.],
       [ 194.,  194.,  194., ...,   60.,   55.,   81.],
       [ 137.,  134.,  135., ...,  135.,  135.,  133.]])

In [19]:
xTrain.astype(float)

array([[  62.,   63.,   88., ...,   70.,   69.,   71.],
       [ 118.,  118.,  118., ...,  116.,  116.,  115.],
       [  81.,   97.,   98., ...,   95.,   87.,   77.],
       ..., 
       [ 109.,  108.,  108., ...,  106.,  106.,  107.],
       [ 194.,  194.,  194., ...,   60.,   55.,   81.],
       [ 137.,  134.,  135., ...,  135.,  135.,  133.]])

In [20]:
#Get only first character of string (convert from string to character).
#Apply the function to each element of the column "Class"
yTrain =  [ord(x[0]) for x in labelsInfoTrain["Class"]]
[ord(x[0]) for x in labelsInfoTrain["Class"]]
#Convert from character to integer
#yTrain = int(yTrain)
#yTrain=yTrain'

[110,
 56,
 84,
 73,
 82,
 87,
 76,
 108,
 75,
 71,
 65,
 65,
 67,
 117,
 116,
 65,
 78,
 73,
 79,
 107,
 108,
 68,
 84,
 117,
 119,
 78,
 69,
 69,
 72,
 101,
 67,
 65,
 78,
 84,
 67,
 65,
 87,
 105,
 79,
 114,
 97,
 48,
 97,
 78,
 72,
 101,
 82,
 49,
 65,
 54,
 111,
 76,
 72,
 65,
 48,
 87,
 49,
 68,
 87,
 73,
 67,
 79,
 76,
 71,
 65,
 69,
 99,
 82,
 65,
 72,
 54,
 111,
 83,
 119,
 78,
 54,
 82,
 69,
 97,
 84,
 50,
 89,
 90,
 82,
 114,
 101,
 108,
 102,
 105,
 78,
 79,
 83,
 69,
 114,
 83,
 74,
 90,
 49,
 114,
 90,
 68,
 105,
 77,
 53,
 69,
 69,
 101,
 83,
 65,
 110,
 100,
 55,
 65,
 69,
 80,
 72,
 54,
 69,
 97,
 84,
 54,
 70,
 82,
 101,
 68,
 111,
 101,
 101,
 84,
 83,
 69,
 114,
 79,
 110,
 114,
 117,
 65,
 72,
 69,
 116,
 65,
 106,
 98,
 80,
 65,
 100,
 113,
 88,
 51,
 52,
 79,
 73,
 69,
 76,
 65,
 110,
 76,
 97,
 97,
 65,
 116,
 84,
 76,
 78,
 68,
 97,
 84,
 85,
 72,
 82,
 73,
 82,
 82,
 106,
 78,
 84,
 67,
 69,
 116,
 85,
 57,
 68,
 78,
 101,
 67,
 73,
 69,
 69,
 116,
 120,
 83,


In [21]:
yTrain=np.array(yTrain)
yTrain=yTrain.T
yTrain

array([110,  56,  84, ...,  80,  78,  82])

In [22]:
trainFinal=np.column_stack((yTrain,xTrain))
trainFinal

array([[ 110.,   62.,   63., ...,   70.,   69.,   71.],
       [  56.,  118.,  118., ...,  116.,  116.,  115.],
       [  84.,   81.,   97., ...,   95.,   87.,   77.],
       ..., 
       [  80.,  109.,  108., ...,  106.,  106.,  107.],
       [  78.,  194.,  194., ...,   60.,   55.,   81.],
       [  82.,  137.,  134., ...,  135.,  135.,  133.]])

In [23]:
trainFinal.dtype


dtype('float64')

In [25]:

np.savetxt("TrainImgForAzure.csv", trainFinal, delimiter=",")

In [26]:
# Test Data preprocessing
labelsInfoTest = pandas.read_csv("C://Users//cr203945//Desktop//Image Recognition using Theano//notebooks//sampleSubmission.csv")
labelsInfoTest


ID Class
0      6284     A
1      6285     A
2      6286     A
3      6287     A
4      6288     A
5      6289     A
6      6290     A
7      6291     A
8      6292     A
9      6293     A
10     6294     A
11     6295     A
12     6296     A
13     6297     A
14     6298     A
15     6299     A
16     6300     A
17     6301     A
18     6302     A
19     6303     A
20     6304     A
21     6305     A
22     6306     A
23     6307     A
24     6308     A
25     6309     A
26     6310     A
27     6311     A
28     6312     A
29     6313     A
...     ...   ...
6190  12474     A
6191  12475     A
6192  12476     A
6193  12477     A
6194  12478     A
6195  12479     A
6196  12480     A
6197  12481     A
6198  12482     A
6199  12483     A
6200  12484     A
6201  12485     A
6202  12486     A
6203  12487     A
6204  12488     A
6205  12489     A
6206  12490     A
6207  12491     A
6208  12492     A
6209  12493     A
6210  12494     A
6211  12495     A
6212  12496     A
6213  12497     A
6214  12498     A
6215  12499     A
6216  12500     A
6217  12501     A
6218  12502     A
6219  12503     A

[6220 rows x 2 columns]

In [38]:
tpath = "C://Users//cr203945//Documents//NEU//Image recognition Project"
xTest = read_data("test", labelsInfoTest, imageSize, path)
xTest.shape

(6283, 400)

In [39]:
xTest.astype(float)

array([[ 114.,  113.,  112., ...,  124.,  122.,  119.],
       [  71.,   72.,   78., ...,  110.,   72.,   75.],
       [  28.,   39.,   39., ...,   36.,   36.,   26.],
       ..., 
       [   0.,    0.,    0., ...,    0.,    0.,    0.],
       [   0.,    0.,    0., ...,    0.,    0.,    0.],
       [   0.,    0.,    0., ...,    0.,    0.,    0.]])

In [42]:

np.savetxt("TestImgForAzure.csv", xTest, delimiter=",")

In [30]:
#Get only first character of string (convert from string to character).
#Apply the function to each element of the column "Class"
yTest =  [ord(x[0]) for x in labelsInfoTest["Class"]]
[ord(x[0]) for x in labelsInfoTest["Class"]]

[65,
 65,
 65,
 65,
 65,
 65,
 65,
 65,
 65,
 65,
 65,
 65,
 65,
 65,
 65,
 65,
 65,
 65,
 65,
 65,
 65,
 65,
 65,
 65,
 65,
 65,
 65,
 65,
 65,
 65,
 65,
 65,
 65,
 65,
 65,
 65,
 65,
 65,
 65,
 65,
 65,
 65,
 65,
 65,
 65,
 65,
 65,
 65,
 65,
 65,
 65,
 65,
 65,
 65,
 65,
 65,
 65,
 65,
 65,
 65,
 65,
 65,
 65,
 65,
 65,
 65,
 65,
 65,
 65,
 65,
 65,
 65,
 65,
 65,
 65,
 65,
 65,
 65,
 65,
 65,
 65,
 65,
 65,
 65,
 65,
 65,
 65,
 65,
 65,
 65,
 65,
 65,
 65,
 65,
 65,
 65,
 65,
 65,
 65,
 65,
 65,
 65,
 65,
 65,
 65,
 65,
 65,
 65,
 65,
 65,
 65,
 65,
 65,
 65,
 65,
 65,
 65,
 65,
 65,
 65,
 65,
 65,
 65,
 65,
 65,
 65,
 65,
 65,
 65,
 65,
 65,
 65,
 65,
 65,
 65,
 65,
 65,
 65,
 65,
 65,
 65,
 65,
 65,
 65,
 65,
 65,
 65,
 65,
 65,
 65,
 65,
 65,
 65,
 65,
 65,
 65,
 65,
 65,
 65,
 65,
 65,
 65,
 65,
 65,
 65,
 65,
 65,
 65,
 65,
 65,
 65,
 65,
 65,
 65,
 65,
 65,
 65,
 65,
 65,
 65,
 65,
 65,
 65,
 65,
 65,
 65,
 65,
 65,
 65,
 65,
 65,
 65,
 65,
 65,
 65,
 65,
 65,
 65,
 65,
 65,


In [35]:
yTest=np.array(yTest)
yTest=yTest.T
yTest.shape, xTest.shape

((6220,), (6283, 400))

In [32]:
testFinal=np.column_stack((yTest,xTest))
testFinal

ValueError: all the input array dimensions except for the concatenation axis must match exactly